baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Laotzu Theme'

# [menus]
#   [[menus.main]]
#     name = 'Главная'
#     pageRef = '/'
#     weight = 10
#
#   [[menus.main]]
#     name = 'Посты'
#     pageRef = '/posts'
#     weight = 20
#
#   [[menus.main]]
#     name = 'Теги'
#     pageRef = '/tags'
#     weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.152.0'
